baseURL: "https://example.com"
languageCode: "en-us"
paginate: 10
title: "clone blog website"
params:
  description: desc for clone blog website
  tags: ["list", "of", "keywords"]
  favicon: https://res.cloudinary.com/rakesh-gupta/image/upload/v1684476786/github-logo_icon-icons.com_73546_voaw1h.ico
  album: https://res.cloudinary.com/rakesh-gupta/image/upload/v1680082086/output_ritppq.webp
  mainSections: ["blog","news"]

taxonomies:
   tag: "tags"
   author: "authors"


author:
  name: rakesh gupta
  email: rakesh.rkgupta29@gmail.com
  phone: 1234567890
menu:
  header:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: blog
      name: Blog
      url: /blog
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags
      weight: 3
